name: Build Windows

on:
  push:
    tags:
      - 'v*'
    branches:
      - feat/besden
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run make:win

      - uses: actions/upload-artifact@v4
        with:
          name: animation-preview-windows
          path: |
            out/make/**/*.exe
            out/make/**/*.nupkg
          if-no-files-found: error
          retention-days: 5

      - if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/**/*.exe
